image: fedora:latest

build_mingw64:
  stage: build
  script:
    - dnf --quiet --assumeyes install mingw64-gcc mingw64-gcc-c++ mingw64-binutils mingw64-headers mingw64-podofo mingw64-qt5-qtbase mingw64-qt5-qttools mingw64-qt5-qttools-tools cmake make
    - export PATH=/usr/x86_64-w64-mingw32/bin:$PATH
    - mkdir -p x86_64-w64-mingw32 mingw64-build; cd x86_64-w64-mingw32
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=/builds/${CI_PROJECT_PATH}/mingw64-build
    - make; make install
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll /builds/${CI_PROJECT_PATH}/mingw64-build/bin/
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5 /builds/${CI_PROJECT_PATH}/mingw64-build/
    - echo "[Paths]" > /builds/${CI_PROJECT_PATH}/mingw64-build/bin/qt.conf
    - echo "Prefix = ../qt5" >> /builds/${CI_PROJECT_PATH}/mingw64-build/bin/qt.conf
  artifacts:
    expire_in: 14d
    paths:
      - ./mingw64-build
  tags:
    - shared

